import React from 'react';
import { Lightbulb, TrendingUp, TrendingDown, AlertCircle } from 'lucide-react';
import { Campaign } from '../../../../lib/agents/marketing/types';

interface CampaignInsightsProps {
  campaign: Campaign;
}

export function CampaignInsights({ campaign }: CampaignInsightsProps) {
  // In a real app, these would be generated by the AI
  const insights = [
    {
      type: 'success',
      title: 'High Engagement on Instagram',
      description: 'Your visual content is performing exceptionally well on Instagram, with 2x higher engagement than average.',
      recommendation: 'Consider increasing Instagram post frequency and budget allocation.'
    },
    {
      type: 'warning',
      title: 'Email Open Rates Declining',
      description: 'Email open rates have dropped 15% in the last week.',
      recommendation: 'Test different subject lines and sending times to improve engagement.'
    },
    {
      type: 'opportunity',
      title: 'Untapped Audience Segment',
      description: 'Data suggests a growing interest from the 25-34 age group.',
      recommendation: 'Create targeted content for this demographic to expand reach.'
    }
  ];

  const getInsightIcon = (type: string) => {
    switch (type) {
      case 'success':
        return <TrendingUp className="h-5 w-5 text-green-500" />;
      case 'warning':
        return <TrendingDown className="h-5 w-5 text-yellow-500" />;
      case 'opportunity':
        return <Lightbulb className="h-5 w-5 text-blue-500" />;
      default:
        return <AlertCircle className="h-5 w-5 text-gray-400" />;
    }
  };

  return (
    <div className="space-y-4">
      {insights.map((insight, index) => (
        <div
          key={index}
          className="bg-white p-4 rounded-lg border border-gray-200"
        >
          <div className="flex items-start space-x-3">
            {getInsightIcon(insight.type)}
            <div>
              <h4 className="text-sm font-medium text-gray-900">{insight.title}</h4>
              <p className="mt-1 text-sm text-gray-500">{insight.description}</p>
              <div className="mt-2 p-2 bg-gray-50 rounded">
                <p className="text-sm font-medium text-indigo-600">
                  Recommendation: {insight.recommendation}
                </p>
              </div>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}